name: Build and Test
on: [push]

jobs:

  frontend:
    name: Build and run frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Prepare Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x

      - name: Create dist dir
        run: mkdir -p dist

      - name: Build (create header)
        run: echo '// Built at' $(date) | cat - src/frontend/app.js > dist/app.js

      - name: Run built frontend for testing
        run: node dist/app.js
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: dist


  backend: 
    name: Build and run backend
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Prepare python
        uses: actions/setup-python@v2

      - name: Create dist dir
        run: mkdir -p dist

      - name: Build (create header)
        run: echo '# Built at' $(date) | cat - src/backend/run.py > dist/run.py

      - name: Run built Backend for testing
        run: python dist/run.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: dist
  
  download:
    name: Download artifacts
    runs-on: ubuntu-latest
    needs: 
      - backend
      - frontend
    
    steps:
      - name: Download backend
        uses: actions/download-artifact@v2
        with:
          name: backend-arti
          path: backend-artifact

      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-arti
          path: frontend-artifact
