name: Frontend
on: [push]

jobs:

  list_files_in_repo:
    name: List repo files
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: List files in repo
        run: cat src/frontend/app.js